// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package plugin

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PluginClient is the client API for Plugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PluginClient interface {
	// GetJobs returns a stream of Job objects.
	// Used to expose jobs to Bhojpur Belaur.
	GetJobs(ctx context.Context, in *Empty, opts ...grpc.CallOption) (Plugin_GetJobsClient, error)
	// ExecuteJob signals the plugin to execute the given job.
	// Used to execute one job from a pipeline.
	ExecuteJob(ctx context.Context, in *Job, opts ...grpc.CallOption) (*JobResult, error)
}

type pluginClient struct {
	cc grpc.ClientConnInterface
}

func NewPluginClient(cc grpc.ClientConnInterface) PluginClient {
	return &pluginClient{cc}
}

func (c *pluginClient) GetJobs(ctx context.Context, in *Empty, opts ...grpc.CallOption) (Plugin_GetJobsClient, error) {
	stream, err := c.cc.NewStream(ctx, &Plugin_ServiceDesc.Streams[0], "/proto.Plugin/GetJobs", opts...)
	if err != nil {
		return nil, err
	}
	x := &pluginGetJobsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Plugin_GetJobsClient interface {
	Recv() (*Job, error)
	grpc.ClientStream
}

type pluginGetJobsClient struct {
	grpc.ClientStream
}

func (x *pluginGetJobsClient) Recv() (*Job, error) {
	m := new(Job)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *pluginClient) ExecuteJob(ctx context.Context, in *Job, opts ...grpc.CallOption) (*JobResult, error) {
	out := new(JobResult)
	err := c.cc.Invoke(ctx, "/proto.Plugin/ExecuteJob", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PluginServer is the server API for Plugin service.
// All implementations must embed UnimplementedPluginServer
// for forward compatibility
type PluginServer interface {
	// GetJobs returns a stream of Job objects.
	// Used to expose jobs to Bhojpur Belaur.
	GetJobs(*Empty, Plugin_GetJobsServer) error
	// ExecuteJob signals the plugin to execute the given job.
	// Used to execute one job from a pipeline.
	ExecuteJob(context.Context, *Job) (*JobResult, error)
	mustEmbedUnimplementedPluginServer()
}

// UnimplementedPluginServer must be embedded to have forward compatible implementations.
type UnimplementedPluginServer struct {
}

func (UnimplementedPluginServer) GetJobs(*Empty, Plugin_GetJobsServer) error {
	return status.Errorf(codes.Unimplemented, "method GetJobs not implemented")
}
func (UnimplementedPluginServer) ExecuteJob(context.Context, *Job) (*JobResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecuteJob not implemented")
}
func (UnimplementedPluginServer) mustEmbedUnimplementedPluginServer() {}

// UnsafePluginServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PluginServer will
// result in compilation errors.
type UnsafePluginServer interface {
	mustEmbedUnimplementedPluginServer()
}

func RegisterPluginServer(s grpc.ServiceRegistrar, srv PluginServer) {
	s.RegisterService(&Plugin_ServiceDesc, srv)
}

func _Plugin_GetJobs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PluginServer).GetJobs(m, &pluginGetJobsServer{stream})
}

type Plugin_GetJobsServer interface {
	Send(*Job) error
	grpc.ServerStream
}

type pluginGetJobsServer struct {
	grpc.ServerStream
}

func (x *pluginGetJobsServer) Send(m *Job) error {
	return x.ServerStream.SendMsg(m)
}

func _Plugin_ExecuteJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Job)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServer).ExecuteJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Plugin/ExecuteJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServer).ExecuteJob(ctx, req.(*Job))
	}
	return interceptor(ctx, in, info, handler)
}

// Plugin_ServiceDesc is the grpc.ServiceDesc for Plugin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Plugin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Plugin",
	HandlerType: (*PluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExecuteJob",
			Handler:    _Plugin_ExecuteJob_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetJobs",
			Handler:       _Plugin_GetJobs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "pkg/api/v1/plugin/plugin.proto",
}
